version: '3'
services:
  dev-app:
    build: .
    image: ui-labs:dev
    command: npm run storybook
    ports:
      - '3000:3000'
    volumes:
      - ./prod/build:/app/storybook-static
    stdin_open: true
    tty: true
  prod-app:
    build: ./prod
    image: registry.gitlab.com/wavelabs/ui-labs:dev
    container_name: dev-ui-labs
    ports:
      - '8084:80'
    restart: always
    stdin_open: true
    tty: true

